title: CharHub AI Documentation
description: Documentation for website charhub.ai
theme: just-the-docs

url: https://rubicolabs.github.io/charhub-docs/
color_scheme: auto
# Custom JavaScript for dark mode toggle
assets:
  scripts:
    - "/assets/js/theme-toggle.js"
